BASEAPP/urls.py
from django.conf.urls import url
from BASEAPP import views

urlpatterns = [
    url(r"^regirst/", views.regirst,name="regirst"),
    url(r"^verify/",views.verify,name="verify"),
    url(r"^get_code_img/",views.Get_code_img,name="get_code_img"),
    url(r"^login/",views.login,name="login"),
    url(r"^Mine/",views.Mine,name="Mine"),
    url(r"^userpic",views.userpicsave,name="userpic"),
    url(r"^submitinfo/",views.submitinfo,name="submitinfo"),
    url(r"^bloglist/",views.bloglist,name="bloglist"),
    url(r"^viewblog/",views.viewblog,name="viewblog"),
]

Blog/urls.py
from django.conf.urls import url
from Blog import views

urlpatterns = [
    url(r"^Editor/",views.Editor,name="Editor"),
    url(r"^Save/",views.Save,name="Save"),
    url(r"^Upload/",views.Upload,name="Upload"),
    url(r"^comment/",views.comment,name="comment"),
]

Channel/urls.py
from django.conf.urls import url
from Channel import views

urlpatterns = [
    url(r"^create/",views.create,name="create"),
    url(r"^channellist/",views.channellist,name="channellist"),
    url(r"^viewchannel",views.viewchannel,name="viewchannel"),
    url(r"^bloglist/",views.bloglist,name="bloglist"),
    url(r"^addblog/",views.addblog,name="addblog"),
    url(r"^removeblog",views.removeblog,name="removeblog"),
    url(r"^bloglistremove",views.bloglistremove,name="bloglistremove"),
    url(r"^indexchannellist/",views.indexchannellist,name="indexchannellist"),
    url(r"^indexchannelsearch/",views.indexchannelsearch,name="indexchannelsearch")

]

WhiteHole/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from BASEAPP import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin"),
    url(r'^Base/',include(("BASEAPP.urls","Base"),namespace="Base")),
    url(r"^Blog/",include(("Blog.urls","Blog"),namespace="Blog")),
    url(r"^Channel/",include(("Channel.urls","Channel"),namespace="Channel")),
    path(r"",views.index,name="index"),
    url(r'mdeditor/', include('mdeditor.urls')),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)主要是让页面显示正常
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Channelslist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <base href="/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
          integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
            crossorigin="anonymous"></script>
</head>
<body>
<div>

    <div class="list-group">

        {% for foo in page_object.object_list %}
            <h4><a href="{% url "Channel:viewchannel"%}?channel_name={{ foo.channel_name }}&channel_wirter={{ foo.channel_user.username }}" class="list-group-item-heading" target="_blank">{{ foo.channel_name }}</a></h4>
            <p class="list-group-item-text">{{ foo.channel_desc}}</p>
        {% endfor %}
    </div>


</div>

<div style="position:absolute;bottom:0;width: 100%;text-align: center">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_object.has_previous %}
                <li>
                    <a href="{% url "Channel:channellist" %}?page={{ page_object.previous_page_number }}&wirter={{ wirter}}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a >
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for page_index in page_range %}
                {% ifequal page_index page_object.number %}
                    <li class="active"><a
                            href="{% url "Channel:channellist" %}?page={{ page_index }}&wirter={{ wirter}}">{{ page_index }}</a></li>
                {% else %}
                    <li><a href="{% url "Channel:channellist" %}?page={{ page_index }}&wirter={{ wirter}}">{{ page_index }}</a></li>

                {% endifequal %}

            {% endfor %}
            {% if page_object.has_next %}
                <li>
                    <a href="{% url "Channel:channellist" %}?page={{ page_object.next_page_number }}&wirter={{ wirter}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a>
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

            {% endif %}

        </ul>
    </nav>
</div>
</div>
</body>
</html>

templates/IndexChannelList.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/stack-interface.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/theme.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/custom.css" rel="stylesheet" type="text/css" media="all"/>

</head>

<body data-smooth-scroll-offset="77">
<div class="nav-container"></div>
<div class="main-container">
    <section class="space--sm">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10 col-lg-8">
                    <div class="masonry masonry-blog-list">
                        <hr>
                        <div class="masonry__container masonry--active">

                            <div class="container">
                                <div class="row text-block">
                                    <div class="col-md-12">
                                        <h3>欢迎查看频道</h3>
                                    </div>
                                </div>
                                <div class="row">
                                    {% for foo in page_object.object_list %}
                                        <div class="col-md-4">
                                            <article class="feature feature-1">
                                                <a href="#" class="block"> <img alt="Image"
                                                                                src="/static/image/bgshowchannel.webp"></a>
                                                <div class="feature__body boxed boxed--border" style="height:178px;">
                                                    <span>{{ foo.channel_name }}</span>
                                                    <p style="font-size: 10px">{{ foo.channel_desc|truncatechars:50 }}</p>
                                                    <a href="{% url "Channel:viewchannel" %}?channel_name={{ foo.channel_name }}&channel_wirter={{ foo.channel_user.username }}">
                                                        查看频道
                                                    </a>
                                                </div>
                                            </article>
                                        </div>
                                    {% endfor %}


                                </div>
                            </div>
                            {% if page_object.has_previous %}
                                <div class="pagination"><a class="pagination__prev"
                                                           href="{% url "Channel:indexchannellist" %}?page={{ page_object.previous_page_number }}"
                                                           title="Previous Page">«</a>
                            {% else %}
                                <div class="pagination"><a class="pagination__prev"  title="Previous Page">«</a>
                            {% endif %}
                            <ol>

                                {% for page_index in page_range %}
                                    {% ifequal page_index page_object.number %}
                                        <li style="background-color: #2C7EEA">
                                            <a href="{% url "Channel:indexchannellist" %}?page={{ page_index }}">{{ page_index }}</a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a href="{% url "Channel:indexchannellist" %}?page={{ page_index }}">{{ page_index }}</a>
                                        </li>
                                    {% endifequal %}
                                {% endfor %}

                            </ol>
                            {% if page_object.has_next %}

                                    <a class="pagination__next"
                                       href="{% url "Channel:indexchannellist" %}?page={{ page_object.next_page_number }}"
                                       title="Next Page">»</a>

                            {% else %}

                                    <a class="pagination__next"  title="Next Page">»</a>

                            {% endif %}
                            </div>

                            </div>


                        </div>
                    </div>
                </div>
    </section>
</div>
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/parallax.js"></script>
<script src="/static/js/isotope.min.js"></script>
<script src="/static/js/smooth-scroll.min.js"></script>
<script src="/static/js/scripts.js"></script>

</body>

</html>

templates/Mine.html
<!doctype html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <title>Mine</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/stack-interface.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/theme-charcoal.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/custom.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/theme.css" rel="stylesheet" type="text/css" media="all"/>

</head>
<style>
    #submit {
        margin-left: 80%;
        width: 20%;
        height: 35px;
        border-width: 0px;
        border-radius: 3px;
        background: #1E90FF;
        cursor: pointer;
        outline: none;
        font-family: Microsoft YaHei;
        color: white;
        font-size: 17px;
    }

    button {
        margin-left: 80%;
        width: 20%;
        height: 35px;
        border-width: 0px;
        border-radius: 3px;
        background: #1E90FF;
        cursor: pointer;
        outline: none;
        font-family: Microsoft YaHei;
        color: white;
        font-size: 17px;
    }
</style>

<body data-smooth-scroll-offset="77">
<div class="nav-container"></div>
<div class="main-container">
    <section class="imagebg space--xxs" data-overlay="4">
        <div class="background-image-holder"><img alt="background" src="/static/image/landing-12.jpg"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <span class="btn btn--sm"><img id="userpic" src="{{ userpic }}"
                                                   style="height: 100px;width:100px ;border-radius:60px;"></span>
                    <br>
                    <span class="btn btn--sm"><p style="width: 100px;">{{ username }}</p></span>
                </div>
            </div>
        </div>
    </section>
    <section class="bg--secondary">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div class="tabs-container tabs--vertical">
                        <ul class="tabs">

                            <li class="active">
                                <div class="tab__title"><span class="h5"><p>编辑简介</p></span></div>
                                <div class="tab__content">
                                    <form action="{% url "Base:submitinfo" %}" method="POST">
                                        <textarea name="userinfo" maxlength="256"
                                                  style="height: 300px;border-radius: 5px;outline: none;"></textarea>
                                        <br>
                                        <button id="submit" style="height: 40px;">保存</button>
                                    </form>
                                </div>
                            </li>

                            <li class="active">
                                <div class="tab__title"><span class="h5"><p>更换头像</p></span></div>
                                <div class="tab__content">

                                    <form action="{% url 'Base:userpic' %}" enctype="multipart/form-data" method="POST">
                                        <div style="background-color:rgb(233, 230, 230); width: 100%; height: 300px;">
                                            <img src="" id="showimg">
                                        </div>
                                        <br>

                                        <input id="file" onchange="changepic(this)" type="file" name="userpic"
                                               style="height: 50px; display:inline-block;width: 50%;">
                                        <button style="height: 40px;position: relative; margin-left: 29%;">确定</button>
                                    </form>
                                </div>
                            </li>
                            <li class="active">
                                <div class="tab__title"><span class="h5"><p>我的简介</p></span></div>
                                <div class="tab__content">
                                    <br>
                                    <br>
                                    <p class="lead">简介: </p>
                                    <p class="lead">{{ userinfo }}</p>
                                </div>
                            </li>
                            <li>
                                <div class="tab__title"><span class="h5"><p>我的频道</p></span></div>
                                <div class="tab__content">
                                    <iframe src="{% url "Channel:channellist" %}" frameborder="0" scrolling="no" width="100%"
                                            height="600px">
                                    </iframe>
                                </div>
                            </li>
                            <li>
                                <div class="tab__title"><span class="h5"><p>我的博客</p></span></div>
                                <div class="tab__content">
                                    <iframe src="{% url "Base:bloglist" %}" frameborder="0" scrolling="no" width="100%"
                                            height="600px">

                                    </iframe>
                                </div>
                            </li>
                            <li>
                                <div class="tab__title"><span class="h5"><p>创建频道</p></span></div>
                                <div class="tab__content">
                                    <iframe src="{% url "Channel:create" %}" frameborder="0" scrolling="no" width="100%"
                                            height="500px">

                                    </iframe>
                                </div>
                            </li>
                            <li>
                                <div class="tab__title"><span class="h5"><p>频道收藏</p></span></div>
                                <div class="tab__content">
                                    <p class="lead"> 频道收藏在做~ing </p>
                                </div>
                            </li>
                            <li>
                                <div class="tab__title"><span class="h5"><p>博文收藏</p></span></div>
                                <div class="tab__content">
                                    <p class="lead">博文收藏在做~ing</p>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/parallax.js"></script>
<script src="/static/js/smooth-scroll.min.js"></script>
<script src="/static/js/scripts.js"></script>
<script>
    function changepic() {
        var reads = new FileReader();
        f = document.getElementById('file').files[0];
        reads.readAsDataURL(f);
        reads.onload = function (e) {
            var showing = document.getElementById('showimg');
            var userpic = document.getElementById('userpic');
            showing.src = this.result;
            showing.style.height = "300px";
            showing.style.width = "100%";
        };
    }
</script>

</body>

</html>

templates/Mine_show.html
<!doctype html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <title>Mine</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/stack-interface.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/theme-charcoal.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/custom.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="/static/css/theme.css" rel="stylesheet" type="text/css" media="all"/>

</head>
<style>
    #submit {
        margin-left: 80%;
        width: 20%;
        height: 35px;
        border-width: 0px;
        border-radius: 3px;
        background: #1E90FF;
        cursor: pointer;
        outline: none;
        font-family: Microsoft YaHei;
        color: white;
        font-size: 17px;
    }

    button {
        margin-left: 80%;
        width: 20%;
        height: 35px;
        border-width: 0px;
        border-radius: 3px;
        background: #1E90FF;
        cursor: pointer;
        outline: none;
        font-family: Microsoft YaHei;
        color: white;
        font-size: 17px;
    }
</style>

<body data-smooth-scroll-offset="77">
<div class="nav-container"></div>
<div class="main-container">
    <section class="imagebg space--xxs" data-overlay="4">
        <div class="background-image-holder"><img alt="background" src="/static/image/landing-12.jpg"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <span class="btn btn--sm"><img id="userpic" src="{{ userpic }}"
                                                   style="height: 100px;width:100px ;border-radius:60px;"></span>
                    <br>
                    <span class="btn btn--sm"><p style="width: 100px;">{{ username }}</p></span>
                </div>
            </div>
        </div>
    </section>
    <section class="bg--secondary">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div class="tabs-container tabs--vertical">
                        <ul class="tabs">
                            <li class="active">
                                <div class="tab__title"><span class="h5"><p>Ta的简介</p></span></div>
                                <div class="tab__content">
                                    <br>
                                    <br>
                                    <p class="lead">简介: </p>
                                    <p class="lead">{{ userinfo }}</p>
                                </div>
                            </li>
                            <li>
                                <div class="tab__title"><span class="h5"><p>Ta的频道</p></span></div>
                                <div class="tab__content">
                                    <iframe src="{% url "Channel:channellist" %}?wirter={{ username }}" frameborder="0"
                                            scrolling="no" width="100%"
                                            height="600px">
                                    </iframe>
                                </div>
                            </li>
                            <li>
                                <div class="tab__title"><span class="h5"><p>Ta的博客</p></span></div>
                                <div class="tab__content">
                                    <iframe src="{% url "Base:bloglist" %}?wirter={{ username }}" frameborder="0"
                                            scrolling="no" width="100%"
                                            height="600px">
                                    </iframe>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/parallax.js"></script>
<script src="/static/js/smooth-scroll.min.js"></script>
<script src="/static/js/scripts.js"></script>
</body>

</html>

templates/NoPower.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
        <link href="/static/css/stack-interface.css" rel="stylesheet" type="text/css" media="all" />
        <link href="/static/css/theme.css" rel="stylesheet" type="text/css" media="all" />
        <link href="/static/css/custom.css" rel="stylesheet" type="text/css" media="all" />

    </head>
    <body data-smooth-scroll-offset="77">
        <div class="nav-container"> </div>
        <div class="main-container">
            <section class="text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-lg-8">
                            <h1>抱歉</h1>
                            <p class="lead">当前用户没有权限！</p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <script src="/static/js/jquery-3.1.1.min.js"></script>
        <script src="/static/js/parallax.js"></script>
        <script src="/static/js/smooth-scroll.min.js"></script>
        <script src="/static/js/scripts.js"></script>

    </body>

</html>

templates/channelifomlistdel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <base href="/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
          integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
            crossorigin="anonymous"></script>
</head>
<body>
<div>

    <div class="list-group">
    {#这里传入的是用户的名字和博客的名字以及所属频道名#}
        {% for foo in page_object.object_list %}
            <h4><a href="{% url "Channel:removeblog" %}?title={{ foo.title }}&username={{ foo.blog_user.username }}&channelname={{ channelname }}" class="list-group-item-heading"><div></div>{{ foo.title }}</a></h4>
            <h4 class="list-group-item-text">{{ foo.date }}</h4>
        {% endfor %}
    </div>


</div>

<div style="position:absolute;bottom:0;width: 100%;text-align: center">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_object.has_previous %}
                <li>
                    <a href="{% url "Channel:bloglistremove" %}?page={{ page_object.previous_page_number }}&wirter={{ wirter }}&channelname={{ channelname }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a>
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for page_index in page_range %}
                {% ifequal page_index page_object.number %}
                    <li class="active"><a
                            href="{% url "Channel:bloglistremove" %}?page={{ page_index }}&wirter={{ wirter }}&channelname={{ channelname }}">{{ page_index }}</a></li>
                {% else %}
                    <li><a href="{% url "Channel:bloglistremove" %}?page={{ page_index }}&wirter={{ wirter }}&channelname={{ channelname }}">{{ page_index }}</a></li>

                {% endifequal %}

            {% endfor %}
            {% if page_object.has_next %}
                <li>
                    <a href="{% url "Channel:bloglistremove" %}?page={{ page_object.next_page_number }}&wirter={{ wirter }}&channelname={{ channelname }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a>
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

            {% endif %}

        </ul>
    </nav>
</div>
</div>
</body>
{{ tips|safe }}
</html>

templates/index.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <title>首页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../static/css/stack-interface.css" rel="stylesheet" type="text/css" media="all">
    <link href="../static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="../static/css/stack-interface.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="../static/css/theme.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="../static/css/custom.css" rel="stylesheet" type="text/css" media="all"/>

</head>

<body data-smooth-scroll-offset="77">
<div class="nav-container">
    <div class="via-1632026291631" via="via-1632026291631" vio="index_daohang">
        <div class="bar bar--sm visible-xs">
            <div class="container">
                <div class="row">
                    <div class="col-3 col-md-2">

                    </div>
                    <div class="col-9 col-md-10 text-right">
                        <a href="#" class="hamburger-toggle" data-toggle-class="#menu2;hidden-xs hidden-sm"> <i
                                class="icon icon--sm stack-interface stack-menu"></i> </a>
                    </div>
                </div>
            </div>
        </div>
        <nav id="menu2" class="bar bar-2 hidden-xs">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 text-center text-left-sm hidden-xs order-lg-2">
                        <div class="bar__module">

                        </div>
                    </div>
                    <div class="col-lg-5 order-lg-1">


                        <div class="bar__module">
                            <ul class="menu-horizontal text-left">
                                {{ userpic }}
                                {#   用户登录后的头像显示#}

                                &nbsp;

                                <li><a href="#">
                                    首页
                                </a></li>
                                <li><a href="{% url "index" %}">刷新</a></li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-5 text-right text-left-xs text-left-sm order-lg-3">
                        <div class="bar__module">
                            <a target="_blank" class="btn btn--sm type--uppercase"
                               href="{% url "Base:regirst" %}"> <span class="btn__text">
                                    注册
                                </span> </a>
                            <a target="_blank" class="btn btn--sm type--uppercase" href="{% url "Base:login" %}"> <span
                                    class="btn__text">登录</span> </a>
                            <a target="_blank" class="btn btn--sm type--uppercase" href="{% url "Blog:Editor" %}"> <span
                                    class="btn__text">创作</span> </a>
                            <a target="_blank" class="btn btn--sm type--uppercase"
                               href="{% url "Channel:indexchannellist" %}"> <span class="btn__text">频道</span> </a>

                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>
<div class="main-container">
    <section class="cover imagebg text-center section--ken-burns height-60" data-overlay="2">
        <div class="background-image-holder"><img alt="background" src="/static/image/knowledge-1.jpg"></div>
        <div class="container pos-vertical-center">
            <div class="row">
                <div class="col-md-10 col-lg-8">
                    <h1>White Hole</h1>
                    <p class="lead">自由，和谐，无约束的技术交流社区</p>
                    <div class="boxed boxed--lg bg--white text-left">
                        <form class="form--horizontal row m-0" action="{% url "Channel:indexchannelsearch" %}"
                              method="post">
                            <div class="col-md-8"><input type="text" name="search" placeholder="频道搜索"></div>
                            <div class="col-md-4">
                                <button type="submit" class="btn btn--primary type--uppercase">搜索</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <iframe src="{% url "Channel:indexchannelsearch" %}?flag={{ flag }}" style="height: 600px">

    </iframe>
</div>
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/parallax.js"></script>
<script src="/static/js/smooth-scroll.min.js"></script>
<script src="/static/js/scripts.js"></script>
{{ tips }}

</body>

</html>